config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
  :registrations => "registrations"}

  get 'users/profile'
  get 'users/admin'

  resources :projects do
    resources :funds
    resources :promises
    resources :user_project_wishlists
  end

  resources :categories


  post 'projects/:id/user_project_wishlists/new' => 'user_project_wishlists#create'
  post 'projects/:id/funds/new' => 'funds#create', as: :fund
  post 'projects/:id/promises/new' => 'promises#create', as: :promise
  get 'users/:id' => 'users#show', as: :user
  get 'users/project/myprojects' => 'projects#user_projects'
  get '/users/fund/index' => 'funds#index'
  delete 'users/:id' => 'users#destroy'
  patch 'users/:id' => 'users#update'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :project
  has_many :user_project_wishlist
  has_many :user_project_fund
  has_many :bank_datum

  after_initialize :init


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.password = Devise.friendly_token[0,20]
    end
  end

  def full_name
    full_name = "#{first_name} #{last_name}"
  end
  def init
    self.isAdmin ||=false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
  def admin
    @users = User.all
    @categories = Category.all
  end
  def show
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(params.require(:user).permit(:isAdmin))
        format.html { redirect_to users_admin_url, notice: 'User updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_admin_url, notice: 'User account successfully cancelled.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin.html.erb
<% if !current_user.isAdmin? %>
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"> YOU DO NOT HAVE PERMISSION TO VISIT THIS SITE</h1>
  </div>
</div>

<% else %>
  <div>
    <div class="col-md-5">
      <p id="notice"><%= notice %></p>
      <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
        <div class="panel-heading">
          <h1 align="center"> Users</h1>
        </div>
        <div class="panel-body">
          <table class="table" >
            <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Full name</th>
              <th scope="col"> Email </th>
              <th scope="col">Is admin?</th>
              <th scope="col">Show profile</th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <th scope="row"><%=user.id%></th>
                  <td><%= user.full_name%></td>
                  <td><%= user.email %></td>
                  <td><% if user.isAdmin? %> Yes <% else %> No <% end %> </td>
                  <td><%= link_to "Visit", user_path(user.id), method: :get%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
        <div class="panel-heading">
          <h1 align="center"> Categories </h1>
        </div>
        <div class="panel-body">
          <table class="table" >
            <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
            </tr>
            </thead>
            <tbody>
            <% @categories.each do |category| %>
              <tr>
                <th scope="row"><%=category.id%></th>
                <td><%= category.name %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <div>
            <%= link_to "Create new category", new_category_path, method: :get %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/profile.html.erb
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"><%= current_user.full_name %>'s Profile</h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">
        <% if current_user.avatar_file_name != nil %>
          <%= image_tag current_user.avatar.url %>
        <% else %>
          <%= image_tag "default.jpg", :alt => "default", :size => "98x120" %>
        <% end %>

      </div>
      <div class="col-md-4">
        <p style="font-size:20px">Email: <%=current_user.email%><p>
        
      </div>
      <div class="col-md-3" >
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Your funded projects", 'fund/index', method: :get %>
        </p>
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Your wishlist", projects_path, style:'display: none', method: :get %>
        </p>
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Your projects", 'project/myprojects', method: :get %>
        </p>

      </div>
      <div class="col-md-3">
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Edit Profile", edit_user_registration_path, method: :get %>
        </p>
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Add payment method", edit_user_registration_path, method: :get %>
        </p>
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Create a new project", new_project_path, method: :get %>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"><%= @user.full_name %>'s Profile</h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">
        <% if @user.avatar_file_name != nil %>
          <%= image_tag @user.avatar.url %>
        <% else %>
          <%= image_tag "default.jpg", :alt => "default", :size => "98x120" %>
        <% end %>

      </div>
      <div class="col-md-4">
        <p style="font-size:20px">Email: <%=@user.email%><p>
        <p style="font-size:15px">Projects Funded: </p>
        <p style="font-size:15px">Projects in wishlist: </p>
        <p style="font-size:15px">Projects created by this user: </p>
      </div>
      <div class="col-md-3" >
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Projects Funded", projects_path, method: :get %>
        </p>
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "Wishlist", projects_path, method: :get %>
        </p>
        <p style="font-size: 20px; font-style: italic">
          <%= link_to "This users' Projects", projects_path, method: :get %>
        </p>
      </div>
      <div class="col-md-3">
        <p style="font-size: 20px; font-style: italic">
          <% if current_user.isAdmin? %>
            <%= link_to "Cancel this account", @user, method: :delete, data: {confirm: 'This account is about to be deleted'} %>
            <%= form_for @user do |f|%>
              <div>
                <%= f.label :isAdmin, "Administrator" %>
                <%= f.check_box :isAdmin %>
              </div>
              <%= f.submit t('.update', default: 'Update privileges'), class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>

  </div>
</div>