config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
  :registrations => "registrations"}

  get 'users/profile'
  get 'users/admin'

  resources :projects do
    resources :funds
    resources :promises
    resources :user_project_wishlists
  end

  resources :categories


  post 'projects/:id/user_project_wishlists/new' => 'user_project_wishlists#create'
  post 'projects/:id/funds/new' => 'funds#create', as: :fund
  post 'projects/:id/promises/new' => 'promises#create', as: :promise
  get 'users/:id' => 'users#show', as: :user
  get 'users/project/myprojects' => 'projects#user_projects'
  get '/users/fund/index' => 'funds#index'
  delete 'users/:id' => 'users#destroy'
  patch 'users/:id' => 'users#update'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user, optional: true
  has_one :user
  has_many :promise
  has_one :category
  has_many :user_project_wishlist
  has_many :user_project_fund

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :category_id, presence: true
  validates :user_id, presence: true
  validates :title,
            numericality: false,
            presence: true
  validates :description,
            presence: true
  validates :goal,
            numericality: true,
            presence: true
  validates :is_outstanding,
            presence:true,
            allow_blank: true,
            default: false
  validate :product_creation_is_not_in_the_past

  def product_creation_is_not_in_the_past
    if finishDate.present? && finishDate < Date.today
      errors.add(:finishDate, "Can't be in the past")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = if params[:term]
                  Project.where('title LIKE ? OR description LIKE ?', "%#{params[:term]}%", "%#{params[:term]}%")
                else
                  Project.all
                end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @promise = Promise.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # GET /projects
  def user_projects
    @projects = Project.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:category_id, :user_id, :title,
                                      :description, :goal, :finishDate,
                                      :mainVideo, :mainImage, :image,
                                      :is_outstanding, :term)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.collection_select(:category_id, Category.all,
                          :id, :name, {:prompt => 'Select a Category',
                               :selected =>@project.category_id}) %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :goal %>
    <%= form.text_field :goal, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :finishDate %>
    <%= form.datetime_select :finishDate, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.file_field :image %>
  </div>
  <div class="form-group">
    <% if signed_in? %>
      <% if current_user.isAdmin? %>
        <%= form.label :is_outstanding, "Outstanding" %>
        <%= form.check_box :is_outstanding %>
      <% end %>
    <% end %>
  </div>
  <div class="field">
    <%= form.submit %>
  </div>

  <%= form.hidden_field :user_id, :value => current_user.id %>


<% end %>

app/views/projects/edit.html.erb
<% if current_user.id != @project.user_id %>

  <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
    <div class="panel-heading">
      <h1 align="center"> YOU DO NOT HAVE PERMISSION TO VISIT THIS SITE</h1>
    </div>
  </div>
<%else%>
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h1>Editing Project</h1>
  </div>
  <div class="panel-body">
  <%= render 'form', project: @project %>

  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>
  </div>
</div>

<%end%>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"> Projects</h1>
  </div>
</div>


<% @projects.each  do |project| %>
  <div class="col-md-3">
    <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
      <div class="panel-heading">
        <h3><%= project.title %></h3>
      </div>
      <div class="panel-body">

        <a href="<%= project_url(project)%>">
          <% if project.image_file_name != nil %>
            <%=image_tag project.image.url(:thumb) %>
          <% else %>
            <%= image_tag "project.jpg", :alt => "default", :size => "220x150"%>
          <% end %>
        </a>
        <p>Category: <%= project.category_id %></p>
        <p>User: <%= project.user_id %> </p>
        <p>Goal: <%= project.goal %></p>
        <p>Finishes on <%= project.finishDate.strftime("%Y-%m-%d") %> at <%= project.finishDate.strftime("%I:%M %P") %> </p>

      </div>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h1>New Project</h1>
  </div>
  <div class="panel-body">
  <%= render 'form', project: @project %>

  <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"> <%= @project.title%> </h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <% if @project.image_file_name != nil %>
          <%=image_tag @project.image.url, :alt => "default", :size => "350x350" %>
        <% else %>
          <%= image_tag "project.jpg", :alt => "default", :size => "350x350" %>
        <% end %>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Description:</strong>
          <%= @project.description %>
        </p>
      </div>
      <div class="col-md-4">
        <p>Category: <%= @project.category_id %></p>
        <p>User: <%= @project.user_id %></p>
        <p>Goal: <%= @project.goal %></p>
        <p>Finishes on <%= @project.finishDate.strftime("%Y-%m-%d") %> at <%= @project.finishDate.strftime("%I:%M %P") %> </p>
        <% if current_user.present? %>
          <% if current_user.id!=@project.user_id%>
            <%= link_to 'Fund', new_project_fund_path(@project.id)%>
            <%= link_to 'Add to wishlist', new_project_user_project_wishlist_path(@project), style: 'display: none' %>

          <%end%>
          <% if current_user.isAdmin? or current_user.id == @project.user_id %>
            <%= link_to 'Add Promise', new_project_promise_path(@project), style:'display: none'%>
            <%= link_to 'Edit this project', edit_project_path(@project.id) %>
            <%= link_to 'Cancel this project', @user, method: :delete, data: {confirm: 'This project is about to be deleted'} %>
          <% end %>
          <% if current_user.isAdmin? %>
            <p>outsatanding?</p>
          <%end%>
        <% end %>



      </div>
      <div>
        <p>Promises: </p>
        <% @promise.each  do |promise| %>
          <% if promise.project_id == @project.id%>
            <p>Date: <%promise.deliveryDate%></p>
            <p>Price: <%promise.price %></p>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/projects/user_projects.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"> Projects</h1>
  </div>
</div>


<% @projects.each  do |project| %>
  <% if current_user.id == project.user_id%>
    <div class="col-md-3">
      <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
        <div class="panel-heading">
          <h3><%= project.title %></h3>
        </div>
        <div class="panel-body">

          <a href="<%= project_url(project)%>">
            <% if project.image_file_name != nil %>
              <%=image_tag project.image.url(:thumb) %>
            <% else %>
              <%= image_tag "project.jpg", :alt => "default", :size => "220x150"%>
            <% end %>
          </a>
          <p>Category: <%= project.category_id %></p>
          <p>User: <%= project.user_id %> </p>
          <p>Goal: <%= project.goal %></p>
          <p>Finishes on <%= project.finishDate.strftime("%Y-%m-%d") %> at <%= project.finishDate.strftime("%I:%M %P") %> </p>

        </div>
      </div>
    </div>
  <%end%>
<% end %>