config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
  :registrations => "registrations"}

  get 'users/profile'
  get 'users/admin'

  resources :projects do
    resources :funds
    resources :promises
    resources :user_project_wishlists
  end

  resources :categories


  post 'projects/:id/user_project_wishlists/new' => 'user_project_wishlists#create'
  post 'projects/:id/funds/new' => 'funds#create', as: :fund
  post 'projects/:id/promises/new' => 'promises#create', as: :promise
  get 'users/:id' => 'users#show', as: :user
  get 'users/project/myprojects' => 'projects#user_projects'
  get '/users/fund/index' => 'funds#index'
  delete 'users/:id' => 'users#destroy'
  patch 'users/:id' => 'users#update'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :project
  validates :name,
            presence: true,
            numericality: false
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @projects = Project.all
    @category = Category.find(params[:id])
  end
  def index
    @categories = Category.all
  end
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: @category }

      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>



<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"> Categories</h1>
    <p align="right">
      <%= link_to 'New Category', new_category_path , method: :get if current_user.present? and current_user.isAdmin?%>
    </p>
  </div>
</div>


<% @categories.each do |category| %>
  <div class="col-md-3">
    <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
      <div class="panel-heading">
        <a href="<%= category_url(category) %>">
          <h3><%= category.name %></h3></a>
      </div>

    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h1>New Category</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', category: @category %>
  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <div class="panel-heading">
    <h1 align="center"><%=@category.name%></h1>
  </div>
</div>


<% @projects.each  do |project| %>
  <% if @category.id == project.category_id%>
    <div class="col-md-3">
      <div class="panel panel-default devise-bs" xmlns:font-size="http://www.w3.org/1999/xhtml">
        <div class="panel-heading">
          <h3><%= project.title %></h3>
        </div>
        <div class="panel-body">

          <a href="<%= project_url(project)%>">
            <% if project.image_file_name != nil %>
              <%=image_tag project.image.url(:thumb) %>
            <% else %>
              <%= image_tag "project.jpg", :alt => "default", :size => "220x150"%>
            <% end %>
          </a>
          <p>Category: <%= project.category_id %></p>
          <p>User: <%= project.user_id %> </p>
          <p>Goal: <%= project.goal %></p>
          <p>Finishes on <%= project.finishDate.strftime("%Y-%m-%d") %> at <%= project.finishDate.strftime("%I:%M %P") %> </p>

        </div>
      </div>
    </div>
  <%end%>
<% end %>