config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
  :registrations => "registrations"}

  get 'users/profile'
  get 'users/admin'

  resources :projects do
    resources :funds
    resources :promises
    resources :user_project_wishlists
  end

  resources :categories


  post 'projects/:id/user_project_wishlists/new' => 'user_project_wishlists#create'
  post 'projects/:id/funds/new' => 'funds#create', as: :fund
  post 'projects/:id/promises/new' => 'promises#create', as: :promise
  get 'users/:id' => 'users#show', as: :user
  get 'users/project/myprojects' => 'projects#user_projects'
  get '/users/fund/index' => 'funds#index'
  delete 'users/:id' => 'users#destroy'
  patch 'users/:id' => 'users#update'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Starfounding" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
  <style type="text/css">
    body, html{
      height: 100%;
      margin: 0;
    }

    .bg {
      background-image: url(<%= asset_path 'Stars.jpg' %>);
      height: 100%;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
    }
  </style>
</head>
<body class="bg">

<div class="navbar navbar-default navbar-static-top navbar-inverse ">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <% if current_user.present? %>
        <span class="icon-bar"></span>
      <% end %>
    </button>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if !current_page?(root_path) %>
          <li><%= link_to "Home", root_path %></li>
        <% end %>
        <li><%= link_to "Projects", projects_path, method: :get if !current_page?(projects_path)%></li>
        <li><%= link_to "Categories", categories_path, method: :get if !current_page?(categories_path)%></li>
        <% if current_user.present? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to current_user.full_name, users_profile_path, method: :get if !current_page?(edit_user_registration_path)%></li>
          <li><%= link_to "Administration settings", users_admin_path, method: :get if current_user.isAdmin? %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path, method: :get if !current_page?(new_user_session_path)%></li>
          <li><%= link_to "Register", new_user_registration_path, method: :get if !current_page?(new_user_registration_path)%></li>
        <% end %>

      </ul>
      <p align="right">
      <%= form_tag(projects_path, method: :get) do %>
        <%= text_field_tag :term, params[:term] %>
        <%= submit_tag 'Search', name:nil %>
      <% end %>
      </p>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <%= bootstrap_flash %>
    <%= yield %>
  </div><!--/row-->
</div> <!-- /container -->

</body>
</html>